# https://jekyllrb.com/docs/

title: HUO Ke Website
description: HUO Ke website hosted by Github Pages.

# https://zendesk.github.io/jekyll-theme-zendesk-garden/
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

# Website sidebar, supported by zendesk theme.
sidebar:
  - label: Algorithms and Data Structures
    children:
      - algo-and-data-structure-overview
  - label: CMU 15445 Database System
    children:
      - cmu-15445-db-overview
      - cmu-15445-db-mem-mgmt-and-buffer-cache
      - cmu-15445-db-hash-tables

# Support content search for this website, supported by zendesk theme.
search_enabled: true
