# https://jekyllrb.com/docs/
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
  - label: CMU 15445 Database
    children:
      - cmu-15445-database-introduction


# plugins:
# - jekyll-remote-theme
